
-- Generated by ORDS REST Data Services 21.2.4.r2431032
-- Schema: WKSP_UNIVESPPI  Date: Sat Nov 19 01:20:01 2022 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WKSP_UNIVESPPI',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'univesp_pi',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'projetodoacao',
      p_base_path      => '/projetodoacao/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'projetodoacao',
      p_pattern        => 'instituicoes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'projetodoacao',
      p_pattern        => 'instituicoes',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select a.ID as codigo,
       a.STRNOME as instituicao,
       a.STRLOUGADOURO as logradouro,
        a.INTNUMERO as numero,
       a.BAIRRO,
       a.INTTELEFONE as telefone,
       a.STREMAIL as email,
       b.STRMUNICIPIO as cidade,
       (select  LISTAGG(d.STRITEM, ''</br>'')
         WITHIN GROUP (ORDER BY d.STRITEM) "Emp_list"
         from INSTITENSACEITOS c, ITENS d
        where c.FKEINSTITUICOES = a.id
        and c.FKEITENS = d.id) as itens
  from INSTITUICOES a, MUNICIPIO b
  where 
    a.FKEMUNICIPIO = b.id
    and b.id = nvl(:P101_MUNICIPIO,b.id)
    and (select  LISTAGG(lpad(d.id,10,0), ''</br>'')
         WITHIN GROUP (ORDER BY d.STRITEM) "Emp_list"
         from INSTITENSACEITOS c, ITENS d
        where c.FKEINSTITUICOES = a.id
        and c.FKEITENS = d.id) like ''%'' || nvl(:P101_ITENS,''%'') || ''%''');

    
        
COMMIT;

END;