DECLARE
V_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES
WHERE TABLE_NAME = 'INSTITUICOES';
IF V_COUNT = 0 THEN
BEGIN
EXECUTE IMMEDIATE '
CREATE TABLE "INSTITUICOES" (
"ID" NUMBER NOT NULL ENABLE,
"STRNOME" VARCHAR2(400) NOT NULL ENABLE,
"STRLOUGADOURO" VARCHAR2(200) NOT NULL ENABLE,
"INTNUMERO" NUMBER NOT NULL ENABLE,
"BAIRRO" VARCHAR2(200)  NOT NULL ENABLE,
"FKEMUNICIPIO" NUMBER  NOT NULL ENABLE,
"INTTELEFONE" NUMBER NOT NULL ENABLE,
"DTMATUALIZACAO" TIMESTAMP (6) NOT NULL ENABLE,
CONSTRAINT "INSTITUICOES_PK" PRIMARY KEY ("ID") ENABLE
)';
DBMS_OUTPUT.PUT_LINE('OPERAÇÃO REALIZADA COM SUCESSO !');
END;
ELSE
DBMS_OUTPUT.PUT_LINE('A TABELA INSTITUICOES JÁ EXISTE NO SISTEMA.');
END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'INSTITUICOES_FK_FKEMUNICIPIO';
IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'ALTER TABLE INSTITUICOES ADD CONSTRAINT "INSTITUICOES_FK_FKEMUNICIPIO" FOREIGN KEY (FKEMUNICIPIO)
REFERENCES MUNICIPIO (ID) ENABLE';
ELSE
DBMS_OUTPUT.PUT_LINE('A FOREIGN KEY INSTITUICOES_FK_FKEMUNICIPIO EXISTE.');
END IF;
END;
/
DECLARE V_COUNT_IDX INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT_IDX FROM USER_INDEXES
WHERE INDEX_NAME = 'INSTITUICOES_IDX_FKEMUNICIPIO'
AND TABLE_NAME = 'INSTITUICOES';
IF V_COUNT_IDX = 0 THEN
EXECUTE IMMEDIATE
'CREATE INDEX "INSTITUICOES_IDX_FKEMUNICIPIO" ON "INSTITUICOES" ("FKEMUNICIPIO")';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE O INDEX INSTITUICOES_IDX_FKEMUNICIPIO');
END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'INSTITUICOES_SEQ';
IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "INSTITUICOES_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE INSTITUICOES_SEQ');
END IF;
END;
/
CREATE trigger "BI_INSTITUICOES"
before insert on "INSTITUICOES"
for each row
begin
if :NEW."ID" is null then
select "INSTITUICOES_SEQ".nextval into :NEW."ID" from sys.dual;
end if;
end;
/
ALTER TRIGGER "BI_INSTITUICOES" ENABLE;
