DECLARE
V_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES
WHERE TABLE_NAME = 'INSTITENSACEITOS';
IF V_COUNT = 0 THEN
BEGIN
EXECUTE IMMEDIATE '
CREATE TABLE "INSTITENSACEITOS" (
"ID" NUMBER NOT NULL ENABLE,
"FKEINSTITUICOES" NUMBER  NOT NULL ENABLE,
"FKEITENS" NUMBER  NOT NULL ENABLE,
"DTMATUALIZACAO" TIMESTAMP (6) NOT NULL ENABLE,
CONSTRAINT "INSTITENSACEITOS_PK" PRIMARY KEY ("ID") ENABLE
)';
DBMS_OUTPUT.PUT_LINE('OPERAÇÃO REALIZADA COM SUCESSO !');
END;
ELSE
DBMS_OUTPUT.PUT_LINE('A TABELA INSTITENSACEITOS JÁ EXISTE NO SISTEMA.');
END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'INSTITENSACEITOS_FK_FKEINSTITUICOES';
IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'ALTER TABLE INSTITENSACEITOS ADD CONSTRAINT "INSTITENSACEITOS_FK_FKEINSTITUICOES" FOREIGN KEY (FKEINSTITUICOES)
REFERENCES INSTITUICOES (ID) ENABLE';
ELSE
DBMS_OUTPUT.PUT_LINE('A FOREIGN KEY INSTITENSACEITOS_FK_FKEINSTITUICOES EXISTE.');
END IF;
END;
/
DECLARE V_COUNT_IDX INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT_IDX FROM USER_INDEXES
WHERE INDEX_NAME = 'INSTITENSACEITOS_IDX_FKEINSTITUICOES'
AND TABLE_NAME = 'INSTITENSACEITOS';
IF V_COUNT_IDX = 0 THEN
EXECUTE IMMEDIATE
'CREATE INDEX "INSTITENSACEITOS_IDX_FKEINSTITUICOES" ON "INSTITENSACEITOS" ("FKEINSTITUICOES")';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE O INDEX INSTITENSACEITOS_IDX_FKEINSTITUICOES');
END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'INSTITENSACEITOS_FK_FKEITENS';
IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'ALTER TABLE INSTITENSACEITOS ADD CONSTRAINT "INSTITENSACEITOS_FK_FKEITENS" FOREIGN KEY (FKEITENS)
REFERENCES ITENS (ID) ENABLE';
ELSE
DBMS_OUTPUT.PUT_LINE('A FOREIGN KEY INSTITENSACEITOS_FK_FKEITENS EXISTE.');
END IF;
END;
/
DECLARE V_COUNT_IDX INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT_IDX FROM USER_INDEXES
WHERE INDEX_NAME = 'INSTITENSACEITOS_IDX_FKEITENS'
AND TABLE_NAME = 'INSTITENSACEITOS';
IF V_COUNT_IDX = 0 THEN
EXECUTE IMMEDIATE
'CREATE INDEX "INSTITENSACEITOS_IDX_FKEITENS" ON "INSTITENSACEITOS" ("FKEITENS")';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE O INDEX INSTITENSACEITOS_IDX_FKEITENS');
END IF;
END;
/
DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO V_COUNT FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'INSTITENSACEITOS_SEQ';
IF V_COUNT = 0 THEN
EXECUTE IMMEDIATE
'CREATE SEQUENCE "INSTITENSACEITOS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
ELSE
DBMS_OUTPUT.PUT_LINE('JÁ EXISTE A SEQUENCE INSTITENSACEITOS_SEQ');
END IF;
END;
/
CREATE trigger "BI_INSTITENSACEITOS"
before insert on "INSTITENSACEITOS"
for each row
begin
if :NEW."ID" is null then
select "INSTITENSACEITOS_SEQ".nextval into :NEW."ID" from sys.dual;
end if;
end;
/
ALTER TRIGGER "BI_INSTITENSACEITOS" ENABLE;
